/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.distributor;

/**
 *
 * @author libby
 */
public class SendDistributionRequest extends javax.swing.JPanel {

    /**
     * Creates new form SendDistributionRequest
     */
    public SendDistributionRequest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbVaccineType = new javax.swing.JComboBox();
        btnSendManufactureRequest = new javax.swing.JButton();
        txtExpectedQuantity = new javax.swing.JTextField();
        lblManufacturer = new javax.swing.JLabel();
        lblExpectedQuantity = new javax.swing.JLabel();
        lblVaccineType = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        txtExpectedQuantity1 = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblManufacturer1 = new javax.swing.JLabel();
        cmbVaccineType1 = new javax.swing.JComboBox();

        cmbVaccineType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVaccineTypeActionPerformed(evt);
            }
        });

        btnSendManufactureRequest.setFont(new java.awt.Font("Courier New", 1, 13)); // NOI18N
        btnSendManufactureRequest.setText("Send Vaccine");
        btnSendManufactureRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendManufactureRequestActionPerformed(evt);
            }
        });

        lblManufacturer.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        lblManufacturer.setText("City:");

        lblExpectedQuantity.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        lblExpectedQuantity.setText("Quantity:");

        lblVaccineType.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        lblVaccineType.setText("State:");

        lblTitle.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        lblTitle.setText("Send Distribution Request");

        txtExpectedQuantity1.setEditable(false);

        btnBack.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblManufacturer1.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        lblManufacturer1.setText("Hospital:");

        cmbVaccineType1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVaccineType1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(88, 88, 88)
                        .addComponent(btnBack)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSendManufactureRequest)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblManufacturer1)
                                .addGap(130, 130, 130)
                                .addComponent(cmbVaccineType1, 0, 151, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblManufacturer)
                                    .addComponent(lblVaccineType, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(138, 138, 138)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbVaccineType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtExpectedQuantity1)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblExpectedQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(txtExpectedQuantity)))
                        .addGap(337, 337, 337))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitle)
                    .addComponent(btnBack))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblManufacturer)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtExpectedQuantity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVaccineType))
                        .addGap(18, 18, 18)
                        .addComponent(cmbVaccineType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblManufacturer1)
                    .addComponent(cmbVaccineType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtExpectedQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblExpectedQuantity))
                .addGap(33, 33, 33)
                .addComponent(btnSendManufactureRequest)
                .addContainerGap(284, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbVaccineTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVaccineTypeActionPerformed

    }//GEN-LAST:event_cmbVaccineTypeActionPerformed

    private void btnSendManufactureRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendManufactureRequestActionPerformed

        Vaccine selectedVaccine = (Vaccine)cmbVaccineType.getSelectedItem();
        if(selectedVaccine == null){
            JOptionPane.showMessageDialog(this, "No qualified vaccine now");
            return;
        }
        // make sure we don't create second batch for the vaccine that alrady has a batch
        if(selectedVaccine.getManufactureStatus()!= null){
            JOptionPane.showMessageDialog(this, "Selected vaccine has already been requested");
            return;
        }

        if(selectedVaccine.getManufactureStatus() == null){
            Manufacturer selectedManufacturer = (Manufacturer)cmbManufacturer.getSelectedItem();
            if(selectedManufacturer == null){
                JOptionPane.showMessageDialog(this, "No available manufacturer now");
                return;
            }

            String expectedReceivedDate = txtExpectedReceivedDate.getText();
            if(txtExpectedReceivedDate.getText().isEmpty() || txtExpectedQuantity.getText().isEmpty()){
                JOptionPane.showMessageDialog(this, "All the blanks must be filled");
                return;
            }

            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            dateFormat.setLenient(false);
            try {
                dateFormat.parse(expectedReceivedDate);
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(this, "Please check the date format");
                return;
            }

            int expectedQuantity;
            try{
                expectedQuantity = Integer.parseInt(txtExpectedQuantity.getText());
            } catch (Exception e){
                JOptionPane.showMessageDialog(this, "Please check the quantity format");
                return;
            }

            // create manufacture request
            // add it to Manufacture Role's main work queue
            ManufactureRequest manufactureRequest = new ManufactureRequest();
            manufactureRequest.setVaccine(selectedVaccine);
            manufactureRequest.setQuantity(expectedQuantity);
            manufactureRequest.setExpectedReceivedDate(expectedReceivedDate);

            Role role = selectedManufacturer.getSpecificRole(RoleType.VACCINE_INVENTORY_MANAGER);
            WorkQueue mainWorkQueue = role.getMainWorkQueue();
            mainWorkQueue.getListOfWorkRequests().add(manufactureRequest);

            // update selected vaccine's manufacture status
            selectedVaccine.setManufactureStatus("Requesting");

            JOptionPane.showMessageDialog(this, "Manufacture request send successfully");

            txtExpectedQuantity.setText("");
            txtExpectedReceivedDate.setText("");
        }
    }//GEN-LAST:event_btnSendManufactureRequestActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed

        userProcessContainer.remove(this);

        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageVaccineCatalogAndAllocation mvc = (ManageVaccineCatalogAndAllocation) component;
        mvc.populateVaccineCatalogTable();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

        evt.getWhen();
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbVaccineType1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVaccineType1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbVaccineType1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSendManufactureRequest;
    private javax.swing.JComboBox cmbVaccineType;
    private javax.swing.JComboBox cmbVaccineType1;
    private javax.swing.JLabel lblExpectedQuantity;
    private javax.swing.JLabel lblManufacturer;
    private javax.swing.JLabel lblManufacturer1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVaccineType;
    private javax.swing.JTextField txtExpectedQuantity;
    private javax.swing.JTextField txtExpectedQuantity1;
    // End of variables declaration//GEN-END:variables
}
