/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nvds.ui;

import nvds.NationalVaccineDistributionSystem;
import nvds.Organization.NvdsParticipatingOrganization;
import nvds.Useraccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 * @author Libby
 * @author Tugume William Mutara
 */
public class MainScreen extends javax.swing.JPanel {

    JPanel accountUserMainWorkAreaJPanel;

    UserAccount organizationEmployeeUserAccount;

    NvdsParticipatingOrganization participatingOrganization;

    NationalVaccineDistributionSystem nvds;

    public MainScreen(JPanel accountUserMainWorkAreaJPanel , UserAccount organizationEmployeeUserAccount , NvdsParticipatingOrganization nvdsParticipatingOrganization , NationalVaccineDistributionSystem nvds) {
        initComponents();
        this.accountUserMainWorkAreaJPanel = accountUserMainWorkAreaJPanel;
        this.organizationEmployeeUserAccount = organizationEmployeeUserAccount;
        this.participatingOrganization = nvdsParticipatingOrganization;
        this.nvds = nvds;

        initializeLoggedInUserWorkArea();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings ( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        menuPanel = new javax.swing.JPanel();
        lblWelcomeMessage = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        loggedInUserWorkAreaJPanel = new javax.swing.JPanel();

        splitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        menuPanel.setBackground(new java.awt.Color(255, 255, 255));

        lblWelcomeMessage.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        lblWelcomeMessage.setText("<WelcomeMsg>");

        btnLogOut.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblWelcomeMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 883, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogOut)
                .addContainerGap())
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(menuPanelLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lblWelcomeMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnLogOut, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        splitPane.setTopComponent(menuPanel);

        loggedInUserWorkAreaJPanel.setBackground(new java.awt.Color(255, 255, 255));
        loggedInUserWorkAreaJPanel.setLayout(new java.awt.CardLayout());
        splitPane.setRightComponent(loggedInUserWorkAreaJPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed

        accountUserMainWorkAreaJPanel.remove(this);
        CardLayout layout = ( CardLayout ) accountUserMainWorkAreaJPanel.getLayout();
        layout.previous(accountUserMainWorkAreaJPanel); // Landing page, login screen
    }//GEN-LAST:event_btnLogOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JLabel lblWelcomeMessage;
    private javax.swing.JPanel loggedInUserWorkAreaJPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables

    private void initializeLoggedInUserWorkArea() {
        lblWelcomeMessage.setText("Welcome to "
                + participatingOrganization.getOrganizationName() + "'s WorkArea, "
                + ((organizationEmployeeUserAccount.getOrganizationEmployee().getOrganizationEmployeeName() != null) ? organizationEmployeeUserAccount.getOrganizationEmployee().getOrganizationEmployeeName() : organizationEmployeeUserAccount.getUsername())
                + "!");

        CardLayout layout = ( CardLayout ) loggedInUserWorkAreaJPanel.getLayout();
        loggedInUserWorkAreaJPanel.add("LoginScreen" , organizationEmployeeUserAccount.getOrganizationEmployeeRole().createWorkArea(loggedInUserWorkAreaJPanel , organizationEmployeeUserAccount , participatingOrganization , nvds));
        layout.next(loggedInUserWorkAreaJPanel);
    }

}
