/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nvds.ui;

import nvds.NationalVaccineDistributionSystemConfiguration;
import nvds.NationalVaccineDistributionSystem;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author libby
 * @author william
 */
public class MainJFrame extends javax.swing.JFrame {

    private final NationalVaccineDistributionSystem nationalVaccineDistributionSystem; // nationalVaccineDistributionSystem object

    public MainJFrame() {
        initComponents();
        this.nationalVaccineDistributionSystem = NationalVaccineDistributionSystemConfiguration.configure(); // initialize the nationalVaccineDistributionSystem object
        setSize(800 , 600); // width and height of the screen
        initializeLoginScreen(); // call the initialize login screen within the main jframe constructor
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings ( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nvdsMainWorkAreaJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nvdsMainWorkAreaJPanel.setBackground(new java.awt.Color(255, 102, 102));
        nvdsMainWorkAreaJPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nvdsMainWorkAreaJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nvdsMainWorkAreaJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() ) {
                if ( "Nimbus".equals(info.getName()) ) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch ( ClassNotFoundException ex ) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE , null , ex);
        } catch ( InstantiationException ex ) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE , null , ex);
        } catch ( IllegalAccessException ex ) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE , null , ex);
        } catch ( javax.swing.UnsupportedLookAndFeelException ex ) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE , null , ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(() -> {
            new MainJFrame().setVisible(true);
        });
    }

    private void initializeLoginScreen() {
        // Create a new login screen JPanel, which includes the main work area and nvds single instance
        JPanel accountUserLoginScreenJPanel = new LoginScreen(nvdsMainWorkAreaJPanel , nationalVaccineDistributionSystem);

        // Add the login screen panel to the main work area with the identifier "LoginScreen"
        nvdsMainWorkAreaJPanel.add("UserAccountLoginScreenJPanel"
                + "" , accountUserLoginScreenJPanel);

        // Obtain the layout manager for the main work area (which should be a CardLayout)
        CardLayout cardLayout = ( CardLayout ) nvdsMainWorkAreaJPanel.getLayout();

        // Switch to the next card in the layout, effectively showing the login screen
        cardLayout.next(nvdsMainWorkAreaJPanel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel nvdsMainWorkAreaJPanel;
    // End of variables declaration//GEN-END:variables
}
